# Web Scraper Configuration
scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 10  # seconds
  max_retries: 3
  retry_delay: 2  # seconds
  concurrent_requests: 5
  respect_robots_txt: true
  rate_limit_delay: 1  # seconds between requests to same domain

# Supported sites configuration
sites:
  amazon:
    enabled: true
    base_url: "https://www.amazon.com"
    selectors:
      title: "#productTitle"
      price: ".a-price-whole, .a-price .a-offscreen, #priceblock_ourprice"
      image: "#landingImage, #imgBlkFront"
      availability: "#availability span"
    search_url: "https://www.amazon.com/s?k={query}"
  
  ebay:
    enabled: true
    base_url: "https://www.ebay.com"
    selectors:
      title: ".x-item-title__mainTitle, h1.it-ttl"
      price: ".x-price-primary, .x-bin-price__content, #prcIsum"
      image: ".ux-image-carousel-item img, #icImg"
      availability: ".x-quantity__availability"
    search_url: "https://www.ebay.com/sch/i.html?_nkw={query}"
  
  walmart:
    enabled: true
    base_url: "https://www.walmart.com"
    selectors:
      title: "h1[itemprop='name'], .prod-ProductTitle"
      price: "[itemprop='price'], .price-characteristic"
      image: ".hover-zoom-hero-image, [data-testid='hero-image-container'] img"
      availability: ".prod-ProductOffer-oosMsg, [data-testid='fulfillment-badge']"
    search_url: "https://www.walmart.com/search?q={query}"
  
  target:
    enabled: true
    base_url: "https://www.target.com"
    selectors:
      title: "h1[data-test='product-title'], .h-display-3"
      price: "[data-test='product-price'], .h-text-bs"
      image: "img[data-test='product-image']"
      availability: "[data-test='availability-text']"
    search_url: "https://www.target.com/s?searchTerm={query}"
  
  bestbuy:
    enabled: true
    base_url: "https://www.bestbuy.com"
    selectors:
      title: ".sku-title, h1.heading-5"
      price: ".priceView-customer-price span[aria-hidden='true'], .priceView-hero-price"
      image: ".primary-image, .shop-media-gallery img"
      availability: ".fulfillment-fulfillment-summary, .add-to-cart-button"
    search_url: "https://www.bestbuy.com/site/searchpage.jsp?st={query}"
  
  newegg:
    enabled: true
    base_url: "https://www.newegg.com"
    selectors:
      title: ".product-title, h1.product-title"
      price: ".price-current, .price-current strong"
      image: ".product-view-img-original, .swiper-slide img"
      availability: ".product-inventory, .product-flag"
    search_url: "https://www.newegg.com/p/pl?d={query}"
  
  etsy:
    enabled: true
    base_url: "https://www.etsy.com"
    selectors:
      title: "h1[data-buy-box-listing-title], .wt-text-body-01"
      price: "[data-buy-box-region='price'], .currency-value"
      image: "[data-carousel-image], .wt-max-width-full img"
      availability: "[data-quantity], .wt-text-caption"
    search_url: "https://www.etsy.com/search?q={query}"
  
  aliexpress:
    enabled: true
    base_url: "https://www.aliexpress.com"
    selectors:
      title: "h1[data-pl='product-title'], .product-title-text"
      price: ".product-price-value, .price--currentPriceText"
      image: ".magnifier-image, .images-view-item img"
      availability: ".product-quantity-tip, .product-info"
    search_url: "https://www.aliexpress.com/wholesale?SearchText={query}"

# Database/Storage settings (optional - for your app integration)
storage:
  enabled: false
  type: "json"  # json, sqlite, postgres, etc.
  path: "scraped_data"

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "scraper.log"
  console: true

